excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://faeezabdrashid.github.io
name: Faeez Creation
description: Blog for Faeez Creation
author: Faeez Abd Rashid
avatar: https://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
comments: true
